name: keepers_note
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+11

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4
  kakao_flutter_sdk: ^1.10.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  photo_view: ^0.15.0
  shared_preferences: ^2.5.5
  image_picker: ^1.2.1
  http_parser: ^4.1.2
  image_cropper: ^12.2.0
  material_design_icons_flutter: ^7.0.7296
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.11

# --- 앱 아이콘 설정 ---
flutter_launcher_icons:
  android: true
  ios: true

  # iOS: 여백 없는 꽉 찬 이미지
  image_path_ios: "assets/icons/icon_ios.png"

  # 안드로이드: 적응형 아이콘
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"

  # 폴백용 기본 경로
  image_path: "assets/images/app_icon.png"

# --- 스플래시 화면 설정 ---
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"
  android_12:
    color: "#ffffff"
    image: "assets/images/splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/resources/
    - assets/images/npcs/
    - assets/images/animals/
    - assets/images/fish/
    - assets/images/insects/
    - assets/images/birds/
    - assets/images/cooking/
    - assets/images/crops/
    - assets/images/ingredients/
    - assets/images/achievements/