name: keepers_note
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4
  kakao_flutter_sdk: ^1.10.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  photo_view: ^0.15.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.11

# --- 앱 아이콘 설정 ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png" # 파일이 실제로 이 경로에 있어야 함
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"

# --- 스플래시 화면 설정 ---
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"
  android_12:
    color: "#ffffff"
    image: "assets/images/splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/